services:
  - type: web
    name: tm-live-backend
    env: node
    plan: starter
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
